// Generated by gencpp from file mvr_robot_control/ActionData.msg
// DO NOT EDIT!


#ifndef MVR_ROBOT_CONTROL_MESSAGE_ACTIONDATA_H
#define MVR_ROBOT_CONTROL_MESSAGE_ACTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mvr_robot_control
{
template <class ContainerAllocator>
struct ActionData_
{
  typedef ActionData_<ContainerAllocator> Type;

  ActionData_()
    : joint_pos()  {
      joint_pos.assign(0.0);
  }
  ActionData_(const ContainerAllocator& _alloc)
    : joint_pos()  {
  (void)_alloc;
      joint_pos.assign(0.0);
  }



   typedef boost::array<float, 1>  _joint_pos_type;
  _joint_pos_type joint_pos;





  typedef boost::shared_ptr< ::mvr_robot_control::ActionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvr_robot_control::ActionData_<ContainerAllocator> const> ConstPtr;

}; // struct ActionData_

typedef ::mvr_robot_control::ActionData_<std::allocator<void> > ActionData;

typedef boost::shared_ptr< ::mvr_robot_control::ActionData > ActionDataPtr;
typedef boost::shared_ptr< ::mvr_robot_control::ActionData const> ActionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvr_robot_control::ActionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvr_robot_control::ActionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvr_robot_control::ActionData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::ActionData_<ContainerAllocator2> & rhs)
{
  return lhs.joint_pos == rhs.joint_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvr_robot_control::ActionData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::ActionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvr_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::ActionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::ActionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::ActionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::ActionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::ActionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::ActionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvr_robot_control::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a07255ea0da1785d1c58f5945b919bcb";
  }

  static const char* value(const ::mvr_robot_control::ActionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa07255ea0da1785dULL;
  static const uint64_t static_value2 = 0x1c58f5945b919bcbULL;
};

template<class ContainerAllocator>
struct DataType< ::mvr_robot_control::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvr_robot_control/ActionData";
  }

  static const char* value(const ::mvr_robot_control::ActionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvr_robot_control::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[1] joint_pos\n"
;
  }

  static const char* value(const ::mvr_robot_control::ActionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvr_robot_control::ActionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvr_robot_control::ActionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvr_robot_control::ActionData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_pos: ";
    if (v.joint_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_pos[i]);
    }
    if (v.joint_pos.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVR_ROBOT_CONTROL_MESSAGE_ACTIONDATA_H
