// Generated by gencpp from file mvr_robot_control/MotorData.msg
// DO NOT EDIT!


#ifndef MVR_ROBOT_CONTROL_MESSAGE_MOTORDATA_H
#define MVR_ROBOT_CONTROL_MESSAGE_MOTORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mvr_robot_control
{
template <class ContainerAllocator>
struct MotorData_
{
  typedef MotorData_<ContainerAllocator> Type;

  MotorData_()
    : header()
    , id(0)
    , kp_(0.0)
    , kd_(0.0)
    , ff_(0.0)
    , pos_des_(0.0)
    , vel_des_(0.0)  {
    }
  MotorData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , kp_(0.0)
    , kd_(0.0)
    , ff_(0.0)
    , pos_des_(0.0)
    , vel_des_(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _id_type;
  _id_type id;

   typedef float _kp__type;
  _kp__type kp_;

   typedef float _kd__type;
  _kd__type kd_;

   typedef float _ff__type;
  _ff__type ff_;

   typedef float _pos_des__type;
  _pos_des__type pos_des_;

   typedef float _vel_des__type;
  _vel_des__type vel_des_;





  typedef boost::shared_ptr< ::mvr_robot_control::MotorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvr_robot_control::MotorData_<ContainerAllocator> const> ConstPtr;

}; // struct MotorData_

typedef ::mvr_robot_control::MotorData_<std::allocator<void> > MotorData;

typedef boost::shared_ptr< ::mvr_robot_control::MotorData > MotorDataPtr;
typedef boost::shared_ptr< ::mvr_robot_control::MotorData const> MotorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvr_robot_control::MotorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvr_robot_control::MotorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvr_robot_control::MotorData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::MotorData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.kp_ == rhs.kp_ &&
    lhs.kd_ == rhs.kd_ &&
    lhs.ff_ == rhs.ff_ &&
    lhs.pos_des_ == rhs.pos_des_ &&
    lhs.vel_des_ == rhs.vel_des_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvr_robot_control::MotorData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::MotorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvr_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::MotorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::MotorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::MotorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::MotorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::MotorData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvr_robot_control::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bed2913051bec1ee3cdf057ad08a302";
  }

  static const char* value(const ::mvr_robot_control::MotorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bed2913051bec1eULL;
  static const uint64_t static_value2 = 0xe3cdf057ad08a302ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvr_robot_control::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvr_robot_control/MotorData";
  }

  static const char* value(const ::mvr_robot_control::MotorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvr_robot_control::MotorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"    int16 id\n"
"    float32 kp_\n"
"    float32 kd_\n"
"    float32 ff_\n"
"    float32 pos_des_ \n"
"    float32 vel_des_\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mvr_robot_control::MotorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvr_robot_control::MotorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.kp_);
      stream.next(m.kd_);
      stream.next(m.ff_);
      stream.next(m.pos_des_);
      stream.next(m.vel_des_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvr_robot_control::MotorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvr_robot_control::MotorData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kp_: ";
    Printer<float>::stream(s, indent + "  ", v.kp_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "kd_: ";
    Printer<float>::stream(s, indent + "  ", v.kd_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ff_: ";
    Printer<float>::stream(s, indent + "  ", v.ff_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pos_des_: ";
    Printer<float>::stream(s, indent + "  ", v.pos_des_);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_des_: ";
    Printer<float>::stream(s, indent + "  ", v.vel_des_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVR_ROBOT_CONTROL_MESSAGE_MOTORDATA_H
