// Generated by gencpp from file mvr_robot_control/ObserveData.msg
// DO NOT EDIT!


#ifndef MVR_ROBOT_CONTROL_MESSAGE_OBSERVEDATA_H
#define MVR_ROBOT_CONTROL_MESSAGE_OBSERVEDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mvr_robot_control
{
template <class ContainerAllocator>
struct ObserveData_
{
  typedef ObserveData_<ContainerAllocator> Type;

  ObserveData_()
    : header()
    , imu_angular_vel()
    , joint_pos()
    , joint_vel()
    , commands()
    , quat_float()  {
      imu_angular_vel.assign(0.0);

      joint_pos.assign(0.0);

      joint_vel.assign(0.0);

      commands.assign(0.0);

      quat_float.assign(0.0);
  }
  ObserveData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , imu_angular_vel()
    , joint_pos()
    , joint_vel()
    , commands()
    , quat_float()  {
  (void)_alloc;
      imu_angular_vel.assign(0.0);

      joint_pos.assign(0.0);

      joint_vel.assign(0.0);

      commands.assign(0.0);

      quat_float.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 3>  _imu_angular_vel_type;
  _imu_angular_vel_type imu_angular_vel;

   typedef boost::array<float, 1>  _joint_pos_type;
  _joint_pos_type joint_pos;

   typedef boost::array<float, 1>  _joint_vel_type;
  _joint_vel_type joint_vel;

   typedef boost::array<float, 3>  _commands_type;
  _commands_type commands;

   typedef boost::array<float, 4>  _quat_float_type;
  _quat_float_type quat_float;





  typedef boost::shared_ptr< ::mvr_robot_control::ObserveData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvr_robot_control::ObserveData_<ContainerAllocator> const> ConstPtr;

}; // struct ObserveData_

typedef ::mvr_robot_control::ObserveData_<std::allocator<void> > ObserveData;

typedef boost::shared_ptr< ::mvr_robot_control::ObserveData > ObserveDataPtr;
typedef boost::shared_ptr< ::mvr_robot_control::ObserveData const> ObserveDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvr_robot_control::ObserveData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvr_robot_control::ObserveData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvr_robot_control::ObserveData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::ObserveData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.imu_angular_vel == rhs.imu_angular_vel &&
    lhs.joint_pos == rhs.joint_pos &&
    lhs.joint_vel == rhs.joint_vel &&
    lhs.commands == rhs.commands &&
    lhs.quat_float == rhs.quat_float;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvr_robot_control::ObserveData_<ContainerAllocator1> & lhs, const ::mvr_robot_control::ObserveData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvr_robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvr_robot_control::ObserveData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvr_robot_control::ObserveData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvr_robot_control::ObserveData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "50eb62f4305c2c959b5563826e09f256";
  }

  static const char* value(const ::mvr_robot_control::ObserveData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x50eb62f4305c2c95ULL;
  static const uint64_t static_value2 = 0x9b5563826e09f256ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvr_robot_control/ObserveData";
  }

  static const char* value(const ::mvr_robot_control::ObserveData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"    float32[3] imu_angular_vel\n"
"    float32[1] joint_pos\n"
"    float32[1] joint_vel\n"
"    float32[3] commands\n"
"    float32[4] quat_float\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mvr_robot_control::ObserveData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.imu_angular_vel);
      stream.next(m.joint_pos);
      stream.next(m.joint_vel);
      stream.next(m.commands);
      stream.next(m.quat_float);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObserveData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvr_robot_control::ObserveData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvr_robot_control::ObserveData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "imu_angular_vel: ";
    if (v.imu_angular_vel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.imu_angular_vel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.imu_angular_vel[i]);
    }
    if (v.imu_angular_vel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_pos: ";
    if (v.joint_pos.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_pos.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_pos[i]);
    }
    if (v.joint_pos.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_vel: ";
    if (v.joint_vel.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_vel.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.joint_vel[i]);
    }
    if (v.joint_vel.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "commands: ";
    if (v.commands.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.commands[i]);
    }
    if (v.commands.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_float: ";
    if (v.quat_float.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.quat_float.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.quat_float[i]);
    }
    if (v.quat_float.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVR_ROBOT_CONTROL_MESSAGE_OBSERVEDATA_H
