# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mvr_robot_control/ObserveData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ObserveData(genpy.Message):
  _md5sum = "50eb62f4305c2c959b5563826e09f256"
  _type = "mvr_robot_control/ObserveData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
    float32[3] imu_angular_vel
    float32[1] joint_pos
    float32[1] joint_vel
    float32[3] commands
    float32[4] quat_float
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','imu_angular_vel','joint_pos','joint_vel','commands','quat_float']
  _slot_types = ['std_msgs/Header','float32[3]','float32[1]','float32[1]','float32[3]','float32[4]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,imu_angular_vel,joint_pos,joint_vel,commands,quat_float

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObserveData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_angular_vel is None:
        self.imu_angular_vel = [0.] * 3
      if self.joint_pos is None:
        self.joint_pos = [0.] * 1
      if self.joint_vel is None:
        self.joint_vel = [0.] * 1
      if self.commands is None:
        self.commands = [0.] * 3
      if self.quat_float is None:
        self.quat_float = [0.] * 4
    else:
      self.header = std_msgs.msg.Header()
      self.imu_angular_vel = [0.] * 3
      self.joint_pos = [0.] * 1
      self.joint_vel = [0.] * 1
      self.commands = [0.] * 3
      self.quat_float = [0.] * 4

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(_get_struct_3f().pack(*self.imu_angular_vel))
      buff.write(_get_struct_1f().pack(*self.joint_pos))
      buff.write(_get_struct_1f().pack(*self.joint_vel))
      buff.write(_get_struct_3f().pack(*self.commands))
      buff.write(_get_struct_4f().pack(*self.quat_float))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.imu_angular_vel = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 4
      self.joint_pos = _get_struct_1f().unpack(str[start:end])
      start = end
      end += 4
      self.joint_vel = _get_struct_1f().unpack(str[start:end])
      start = end
      end += 12
      self.commands = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 16
      self.quat_float = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      buff.write(self.imu_angular_vel.tostring())
      buff.write(self.joint_pos.tostring())
      buff.write(self.joint_vel.tostring())
      buff.write(self.commands.tostring())
      buff.write(self.quat_float.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 12
      self.imu_angular_vel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 4
      self.joint_pos = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=1)
      start = end
      end += 4
      self.joint_vel = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=1)
      start = end
      end += 12
      self.commands = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 16
      self.quat_float = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_1f = None
def _get_struct_1f():
    global _struct_1f
    if _struct_1f is None:
        _struct_1f = struct.Struct("<1f")
    return _struct_1f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
